makecode:
  target: microbit
  platform: microbit
  home_url: https://makecode.microbit.org/
theme: jekyll-theme-modernist
asignatura: Aprendizaje y Enseñanza de la Tecnología
lista_de_la_compra:
  - papas
  - tomates
  - huevos
include:
  - assets
  - README.md
